name: "CC BY-NC-SA 4.0"
spdx-id: "CC-BY-NC-SA-4.0"
redirect_from: /licenses/cc-by-nc-sa-4.0/
description: "允许非商业性使用，要求署名并以相同方式共享"
permissions:
  - commercial-use: false
  - distribution: true
  - modifications: true
  - private-use: true
conditions:
  - include-copyright
  - document-changes
  - same-license
limitations:
  - liability
  - trademark-use
  - patent-use
  - warranty
